// import type { Metadata } from "next";
// import { Inter } from "next/font/google";
// import "./globals.css";
// import Header from "../component/layout/Header";
// import Footer from "@/component/layout/Footer";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>
//         <Header />
//         {children}
//         <Footer />
        
//         </body>
//     </html>
//   );
// }


// app/layout.tsx (or app/layout.js if you're not using TypeScript)
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "../component/layout/Header"; // Ensure the path is correct
import Footer from "../component/layout/Footer"; // Ensure the path is correct

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <div className="pt-16"> {/* Adjust padding based on your header height */}
          {children}
        </div>
        <Footer />
      </body>
    </html>
  );
}